apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: testnet-casperhaproxy-cert
spec:
  secretName: testnet-casperhaproxy-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rpc.testnet.casperholders.com
  dnsNames:
    - rpc.testnet.casperholders.com
