apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: casperhaproxy-cert
spec:
  secretName: casperhaproxy-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rpc.casperholders.com
  dnsNames:
    - rpc.casperholders.com
